[project]
name = "Tlacuilo"
version = "0.1.0"
description = "ToDo list ESC/POS API for thermal printers"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "fastapi[standard]==0.133.0",
  "pyfiglet>=1.0.2",
  "python-dotenv>=1.2.1",
  "python-escpos[serial,usb]>=3.1",
]

[project.scripts]
tlacuilo = "tlacuilo.api.routes:main"

[dependency-groups]
dev = [
  "pytest>=9.0.2",
  "pytest-cov>=7.0.0",
  "ruff>=0.14.14",
  "ty>=0.0.14",
  "vulture>=2.14",
]

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.ruff.lint]
ignore = ["S701", "S104", "E722"]
extend-select = ["B", "S", "SIM", "T20", "C901"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = false
