name: pytest
on:
    push:
    pull_request:
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - name: Set up Python
              uses: actions/setup-python@v7
              with:
                  python-version-file: "pyproject.toml"

            - name: Install uv
              uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
              with:
                  enable-cache: true
                  version: 0.12.*

            - name: Install dependencies
              run: uv sync --locked

            - name: Run tests (with coverage)
              run: |
                  uv run pytest \
                    --junitxml=pytest.xml \
                    --cov-report=term-missing:skip-covered \
                    --cov=. \
                    | tee pytest-coverage.txt

            - name: Pytest coverage comment
              uses: MishaKav/pytest-coverage-comment@432ac90e8d345c93e1d90ee0838b35913abc9c9b # main
              with:
                  pytest-coverage-path: ./pytest-coverage.txt
                  junitxml-path: ./pytest.xml
